# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23d9cfe7f9b8308459018cc5ffc784ffb41197ef1dd3a824ef423d45d79805b5cdd73d6363f8ffba276eb4da90bdb930e2fffe513ce4063531dbc3f8bf692a0b

test:
  secret_key_base: 58cdd3b529949077889ff2b00741ecb5d7b85047f6783fa3f108f18fd8cd182277f8405c1c665cc44b7fdd6e06c652ba3d3c0a8a4791929f9316300760b0a66b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
